export type ChargerStatus = "disponible" | "ocupado" | "fuera-de-servicio"
export type ChargerType = "publico" | "privado"
export type ConnectorType = "CCS2" | "Tipo 2" | "CCS1" | "Tipo 1" | "GB/T"
export type DocumentStatus = "vigente" | "por-vencer" | "vencido" | "no-cargado"

export type Charger = {
  id: string
  name: string
  address: string
  city: string
  type: ChargerType
  status: ChargerStatus
  connectors: ConnectorType[]
  power: number // kW
  pricePerKwh: number // COP
  rating: number
  reviews: number
  distanceKm: number
  estimatedWaitMin: number
  /** percent x/y position on the mock map (0-100) */
  mapX: number
  mapY: number
  photo: string
  host?: {
    name: string
    avatar: string
    neighborhood: string
    rating: number
    sessions: number
    verified: boolean
    rules: string[]
  }
  amenities: string[]
}

export const chargers: Charger[] = [
  {
    id: "terpel-voltex-c100",
    name: "Terpel Voltex Calle 100",
    address: "Calle 100 #15-23",
    city: "Bogotá",
    type: "publico",
    status: "disponible",
    connectors: ["CCS2", "Tipo 2"],
    power: 150,
    pricePerKwh: 1450,
    rating: 4.8,
    reviews: 312,
    distanceKm: 1.2,
    estimatedWaitMin: 0,
    mapX: 62,
    mapY: 28,
    photo: "/charger-terpel-station-modern.jpg",
    amenities: ["Iluminación", "Cámara", "24/7", "Café cercano"],
  },
  {
    id: "cc-andino",
    name: "Centro Comercial Andino",
    address: "Carrera 11 #82-71",
    city: "Bogotá",
    type: "publico",
    status: "ocupado",
    connectors: ["CCS2", "Tipo 2", "CCS1"],
    power: 50,
    pricePerKwh: 1290,
    rating: 4.5,
    reviews: 198,
    distanceKm: 2.4,
    estimatedWaitMin: 22,
    mapX: 35,
    mapY: 52,
    photo: "/shopping-mall-ev-charger-underground-parking.jpg",
    amenities: ["Parqueadero techado", "Restaurantes", "Seguridad"],
  },
  {
    id: "parq-chapinero",
    name: "Parqueadero Chapinero EV",
    address: "Calle 63 #11-50",
    city: "Bogotá",
    type: "publico",
    status: "disponible",
    connectors: ["Tipo 2", "GB/T"],
    power: 22,
    pricePerKwh: 980,
    rating: 4.2,
    reviews: 76,
    distanceKm: 3.1,
    estimatedWaitMin: 0,
    mapX: 48,
    mapY: 70,
    photo: "/urban-parking-lot-with-ev-chargers.jpg",
    amenities: ["Acceso 24h", "Iluminación"],
  },
  {
    id: "host-cedritos",
    name: "Cargador residencial Cedritos",
    address: "Carrera 18 #140-22",
    city: "Bogotá",
    type: "privado",
    status: "disponible",
    connectors: ["Tipo 2"],
    power: 11,
    pricePerKwh: 850,
    rating: 4.9,
    reviews: 41,
    distanceKm: 4.8,
    estimatedWaitMin: 0,
    mapX: 78,
    mapY: 18,
    photo: "/private-home-wallbox-charger-garage.jpg",
    host: {
      name: "Andrés Vélez",
      avatar: "/man-smiling-portrait.png",
      neighborhood: "Cedritos",
      rating: 4.9,
      sessions: 124,
      verified: true,
      rules: ["Acceso por portería", "Notificar al llegar", "Máximo 4 horas"],
    },
    amenities: ["Portería 24h", "Cámara", "Acceso privado"],
  },
  {
    id: "host-melgar",
    name: "Punto Anfitrión Melgar",
    address: "Vía Panamericana km 3",
    city: "Melgar",
    type: "privado",
    status: "disponible",
    connectors: ["CCS2", "Tipo 2"],
    power: 22,
    pricePerKwh: 1100,
    rating: 4.7,
    reviews: 28,
    distanceKm: 95,
    estimatedWaitMin: 0,
    mapX: 22,
    mapY: 80,
    photo: "/country-house-ev-charger-with-pool.jpg",
    host: {
      name: "María Camila Ríos",
      avatar: "/woman-smiling-portrait.png",
      neighborhood: "Melgar",
      rating: 4.7,
      sessions: 64,
      verified: true,
      rules: ["Cita previa", "Acceso vehicular directo", "Disponible 7am-9pm"],
    },
    amenities: ["Iluminación", "Zona social", "Wifi"],
  },
  {
    id: "estacion-girardot",
    name: "Estación Girardot",
    address: "Calle 22 #10-15",
    city: "Girardot",
    type: "publico",
    status: "disponible",
    connectors: ["CCS2", "GB/T"],
    power: 60,
    pricePerKwh: 1250,
    rating: 4.4,
    reviews: 52,
    distanceKm: 132,
    estimatedWaitMin: 0,
    mapX: 12,
    mapY: 90,
    photo: "/highway-ev-charging-station-with-lights.jpg",
    amenities: ["24/7", "Cafetería", "Baños"],
  },
  {
    id: "punto-ibague",
    name: "Punto EV Ibagué",
    address: "Av. Mirolindo #45-12",
    city: "Ibagué",
    type: "publico",
    status: "fuera-de-servicio",
    connectors: ["CCS2"],
    power: 50,
    pricePerKwh: 1300,
    rating: 4.0,
    reviews: 19,
    distanceKm: 215,
    estimatedWaitMin: 0,
    mapX: 6,
    mapY: 60,
    photo: "/ev-charging-station-night.jpg",
    amenities: ["Iluminación"],
  },
  {
    id: "enel-x-usaquen",
    name: "Enel X Usaquén",
    address: "Carrera 7 #119-40",
    city: "Bogotá",
    type: "publico",
    status: "disponible",
    connectors: ["CCS2", "Tipo 2"],
    power: 100,
    pricePerKwh: 1380,
    rating: 4.6,
    reviews: 145,
    distanceKm: 1.8,
    estimatedWaitMin: 0,
    mapX: 55,
    mapY: 22,
    photo: "/charger-terpel-station-modern.jpg",
    amenities: ["24/7", "Iluminación", "Cámara", "Wifi"],
  },
  {
    id: "celsia-unicentro",
    name: "Celsia Unicentro",
    address: "Av. 15 #124-30",
    city: "Bogotá",
    type: "publico",
    status: "disponible",
    connectors: ["CCS2", "Tipo 2", "CCS1"],
    power: 50,
    pricePerKwh: 1200,
    rating: 4.4,
    reviews: 89,
    distanceKm: 2.9,
    estimatedWaitMin: 10,
    mapX: 42,
    mapY: 35,
    photo: "/shopping-mall-ev-charger-underground-parking.jpg",
    amenities: ["Parqueadero techado", "Centro comercial", "Seguridad"],
  },
  {
    id: "terpel-voltex-suba",
    name: "Terpel Voltex Suba",
    address: "Av. Suba #115-80",
    city: "Bogotá",
    type: "publico",
    status: "ocupado",
    connectors: ["CCS2", "Tipo 2"],
    power: 150,
    pricePerKwh: 1450,
    rating: 4.7,
    reviews: 203,
    distanceKm: 5.2,
    estimatedWaitMin: 15,
    mapX: 28,
    mapY: 15,
    photo: "/charger-terpel-station-modern.jpg",
    amenities: ["24/7", "Tienda", "Café", "Baños"],
  },
  {
    id: "host-country-chia",
    name: "Cargador Country Chía",
    address: "Vereda Fagua, Lote 12",
    city: "Chía",
    type: "privado",
    status: "disponible",
    connectors: ["Tipo 2"],
    power: 22,
    pricePerKwh: 900,
    rating: 5.0,
    reviews: 18,
    distanceKm: 22,
    estimatedWaitMin: 0,
    mapX: 70,
    mapY: 8,
    photo: "/country-house-ev-charger-with-pool.jpg",
    host: {
      name: "Juliana Moreno",
      avatar: "/woman-smiling-portrait.png",
      neighborhood: "Chía",
      rating: 5.0,
      sessions: 52,
      verified: true,
      rules: ["Solo con reserva", "Acceso por portería", "Horario 6am-10pm"],
    },
    amenities: ["Zona verde", "Wifi", "Seguridad privada"],
  },
  {
    id: "enel-x-cali",
    name: "Enel X Ciudad Jardín",
    address: "Calle 16 #100-50",
    city: "Cali",
    type: "publico",
    status: "disponible",
    connectors: ["CCS2", "Tipo 2"],
    power: 60,
    pricePerKwh: 1350,
    rating: 4.5,
    reviews: 67,
    distanceKm: 460,
    estimatedWaitMin: 0,
    mapX: 15,
    mapY: 45,
    photo: "/ev-charging-station-night.jpg",
    amenities: ["24/7", "Iluminación", "Baños"],
  },
  {
    id: "celsia-medellin",
    name: "Celsia El Poblado",
    address: "Carrera 43A #1-50",
    city: "Medellín",
    type: "publico",
    status: "disponible",
    connectors: ["CCS2", "Tipo 2", "GB/T"],
    power: 100,
    pricePerKwh: 1280,
    rating: 4.8,
    reviews: 178,
    distanceKm: 415,
    estimatedWaitMin: 0,
    mapX: 30,
    mapY: 40,
    photo: "/charger-terpel-station-modern.jpg",
    amenities: ["Café", "Iluminación", "Cámara", "24/7"],
  },
  {
    id: "host-villa-leyva",
    name: "Eco Cargador Villa de Leyva",
    address: "Vereda Centro, Finca El Roble",
    city: "Villa de Leyva",
    type: "privado",
    status: "disponible",
    connectors: ["Tipo 2"],
    power: 11,
    pricePerKwh: 800,
    rating: 4.8,
    reviews: 34,
    distanceKm: 165,
    estimatedWaitMin: 0,
    mapX: 85,
    mapY: 30,
    photo: "/private-home-wallbox-charger-garage.jpg",
    host: {
      name: "Carlos Pinzón",
      avatar: "/man-smiling-portrait.png",
      neighborhood: "Villa de Leyva",
      rating: 4.8,
      sessions: 87,
      verified: true,
      rules: ["Reserva con 2h de anticipación", "Acceso directo", "Máximo 6 horas"],
    },
    amenities: ["Zona social", "Wifi", "Vista panorámica"],
  },
  {
    id: "rapid-charge-tunja",
    name: "Rapid Charge Tunja",
    address: "Av. Norte #48-20",
    city: "Tunja",
    type: "publico",
    status: "disponible",
    connectors: ["CCS2"],
    power: 120,
    pricePerKwh: 1400,
    rating: 4.3,
    reviews: 42,
    distanceKm: 130,
    estimatedWaitMin: 0,
    mapX: 80,
    mapY: 25,
    photo: "/highway-ev-charging-station-with-lights.jpg",
    amenities: ["24/7", "Tienda", "Baños"],
  },
]

export const popularRoutes = [
  { id: "bog-melgar", from: "Bogotá", to: "Melgar", distance: 98, time: "2h 10m", elevation: -1850 },
  { id: "bog-girardot", from: "Bogotá", to: "Girardot", distance: 134, time: "3h", elevation: -2280 },
  { id: "bog-villaleyva", from: "Bogotá", to: "Villa de Leyva", distance: 165, time: "3h 30m", elevation: -440 },
  { id: "med-guatape", from: "Medellín", to: "Guatapé", distance: 79, time: "2h", elevation: 540 },
  { id: "cal-pereira", from: "Cali", to: "Pereira", distance: 215, time: "4h 20m", elevation: 470 },
  { id: "bog-tunja", from: "Bogotá", to: "Tunja", distance: 130, time: "2h 40m", elevation: 180 },
  { id: "bog-bucaramanga", from: "Bogotá", to: "Bucaramanga", distance: 395, time: "7h 30m", elevation: -1600 },
  { id: "med-santafe", from: "Medellín", to: "Santa Fe de Antioquia", distance: 62, time: "1h 30m", elevation: -1100 },
  { id: "bog-chia", from: "Bogotá", to: "Chía", distance: 28, time: "45m", elevation: -50 },
  { id: "cal-buga", from: "Cali", to: "Buga", distance: 74, time: "1h 20m", elevation: 60 },
]

export const vehicleCatalog = [
  { brand: "BYD", models: ["Seagull", "Yuan Plus", "Dolphin", "Han EV", "Seal", "Tang EV", "Atto 3"] },
  { brand: "MG", models: ["S5 EV", "ZS EV", "MG4", "Marvel R"] },
  { brand: "Renault", models: ["Kwid E-Tech", "Megane E-Tech", "Zoe"] },
  { brand: "Volvo", models: ["EX30", "EX40", "XC40 Recharge", "C40 Recharge"] },
  { brand: "Tesla", models: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"] },
  { brand: "Kia", models: ["EV5", "EV6", "EV9", "Niro EV"] },
  { brand: "Hyundai", models: ["Ioniq 5", "Ioniq 6", "Kona Electric"] },
  { brand: "BMW", models: ["iX1", "iX3", "i4", "i5", "i7", "iX"] },
  { brand: "Mercedes-Benz", models: ["EQA", "EQB", "EQC", "EQE", "EQS"] },
  { brand: "Audi", models: ["Q4 e-tron", "Q8 e-tron", "e-tron GT"] },
  { brand: "Porsche", models: ["Taycan", "Macan Electric"] },
  { brand: "Volkswagen", models: ["ID.3", "ID.4", "ID.5", "ID.Buzz"] },
  { brand: "Nissan", models: ["Leaf", "Ariya"] },
  { brand: "Chevrolet", models: ["Bolt EV", "Bolt EUV", "Equinox EV", "Blazer EV"] },
  { brand: "Ford", models: ["Mustang Mach-E", "F-150 Lightning"] },
  { brand: "Peugeot", models: ["e-208", "e-2008", "e-308"] },
  { brand: "MINI", models: ["Cooper SE", "Countryman SE"] },
  { brand: "Fiat", models: ["500e"] },
  { brand: "JAC", models: ["E10X", "iEV40", "iEV7S"] },
  { brand: "Chery", models: ["iCar 03", "eQ7"] },
]

export const services = [
  {
    id: "lavado-premium",
    category: "Lavado premium",
    name: "Aqua Detail Studio",
    city: "Bogotá",
    rating: 4.9,
    priceFrom: 85000,
    photo: "/luxury-car-wash-detailing-studio.jpg",
    available: true,
  },
  {
    id: "detailing-ceramic",
    category: "Detailing",
    name: "Ceramic Pro Bogotá",
    city: "Bogotá",
    rating: 4.8,
    priceFrom: 1200000,
    photo: "/car-ceramic-coating-application.jpg",
    available: true,
  },
  {
    id: "mecanica-ev",
    category: "Mecánica EV",
    name: "EV Service Center",
    city: "Bogotá",
    rating: 4.7,
    priceFrom: 180000,
    photo: "/ev-mechanic-workshop-with-electric-vehicle.jpg",
    available: true,
  },
  {
    id: "wallbox-install",
    category: "Instalación de cargadores",
    name: "Wallbox Instaladores",
    city: "Bogotá",
    rating: 4.9,
    priceFrom: 950000,
    photo: "/wallbox-charger-installation-home.jpg",
    available: true,
  },
  {
    id: "asistencia-ev",
    category: "Asistencia",
    name: "Asistencia EV 24/7",
    city: "Bogotá",
    rating: 4.6,
    priceFrom: 0,
    photo: "/ev-roadside-assistance-tow-truck.jpg",
    available: false,
  },
]

export const documentTemplates: { id: string; name: string; status: DocumentStatus; expiresAt: string | null }[] = [
  { id: "soat", name: "SOAT", status: "por-vencer", expiresAt: "2026-05-22" },
  { id: "todo-riesgo", name: "Seguro todo riesgo", status: "vigente", expiresAt: "2027-02-14" },
  { id: "tecnomec", name: "Revisión técnico-mecánica", status: "vigente", expiresAt: "2026-11-08" },
  { id: "asistencia", name: "Asistencia en carretera", status: "no-cargado", expiresAt: null },
  { id: "licencia", name: "Licencia de conducción", status: "vigente", expiresAt: "2029-04-30" },
]

export const chargingHistory = [
  {
    id: "h1",
    date: "28 abr 2026",
    location: "Terpel Voltex Calle 100",
    kwh: 32.4,
    cost: 46980,
    method: "Tarjeta •• 4821",
    rating: 5,
  },
  {
    id: "h2",
    date: "22 abr 2026",
    location: "Centro Comercial Andino",
    kwh: 18.2,
    cost: 23478,
    method: "PSE",
    rating: 4,
  },
  {
    id: "h3",
    date: "14 abr 2026",
    location: "Host privado Cedritos",
    kwh: 24.0,
    cost: 20400,
    method: "Tarjeta •• 4821",
    rating: 5,
  },
  {
    id: "h4",
    date: "06 abr 2026",
    location: "Estación Girardot",
    kwh: 41.5,
    cost: 51875,
    method: "Tarjeta •• 4821",
    rating: 4,
  },
  {
    id: "h5",
    date: "01 abr 2026",
    location: "Enel X Usaquén",
    kwh: 28.6,
    cost: 39468,
    method: "Nequi",
    rating: 5,
  },
  {
    id: "h6",
    date: "25 mar 2026",
    location: "Celsia Unicentro",
    kwh: 15.8,
    cost: 18960,
    method: "Tarjeta •• 4821",
    rating: 4,
  },
  {
    id: "h7",
    date: "18 mar 2026",
    location: "Terpel Voltex Suba",
    kwh: 36.2,
    cost: 52490,
    method: "PSE",
    rating: 5,
  },
  {
    id: "h8",
    date: "10 mar 2026",
    location: "Cargador Country Chía",
    kwh: 20.0,
    cost: 18000,
    method: "Tarjeta •• 4821",
    rating: 5,
  },
  {
    id: "h9",
    date: "02 mar 2026",
    location: "Rapid Charge Tunja",
    kwh: 44.1,
    cost: 61740,
    method: "Daviplata",
    rating: 3,
  },
  {
    id: "h10",
    date: "22 feb 2026",
    location: "Eco Cargador Villa de Leyva",
    kwh: 22.5,
    cost: 18000,
    method: "Tarjeta •• 4821",
    rating: 5,
  },
]

export const routeHistory = [
  {
    id: "r1",
    from: "Bogotá",
    to: "Melgar",
    estConsumption: 22.4,
    initialBattery: 92,
    finalBattery: 38,
    date: "12 abr 2026",
  },
  {
    id: "r2",
    from: "Bogotá",
    to: "Villa de Leyva",
    estConsumption: 28.1,
    initialBattery: 100,
    finalBattery: 24,
    date: "27 mar 2026",
  },
]

export const badges = [
  { id: "primer-cargon", name: "Primer Cargón", earned: true, description: "Completaste tu primera carga." },
  { id: "explorador", name: "Explorador", earned: true, description: "Visitaste 5 estaciones distintas." },
  { id: "ruta-inteligente", name: "Ruta Inteligente", earned: true, description: "Planeaste tu primer viaje." },
  { id: "anfitrion-verificado", name: "Anfitrión Verificado", earned: false, description: "Publica tu cargador y recibe 5 sesiones." },
  { id: "pionero-ev", name: "Pionero EV", earned: false, description: "1 año en Plugo con uso constante." },
  { id: "cero-ansiedad", name: "Cero Ansiedad", earned: true, description: "10 viajes planeados con éxito." },
]

export const formatCOP = (value: number) =>
  new Intl.NumberFormat("es-CO", { style: "currency", currency: "COP", maximumFractionDigits: 0 }).format(value)
